theme: jekyll-theme-slate
title: [Introduction to SQL]
description: [This page contains the material covered in a training session.]
menus: header
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

navbar:
  left:
    - text: "Home"
      href: index.md
    - text: "Day 1"
      menu:
        - text: "SQL"
          href: day1.md
