theme: jekyll-theme-slate
title: [SQL]
description: [This page contains the material covered in a training session.]
menus: header
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - day1.md
  - README.md

